### ISSUE TITLE
Errors reported on `ValheimExportHelper.FixWAVs` stage

### ISSUE THREAD

**Issue by kirilloid** [Valheim-Modding/Wiki#5]
Since 0.212.9 in the game they optimized resources, specifically this last line in patchnotes:
- Sounds, music, animations and textures have been optimised to save around 485 Mb of RAM and to decrease the download size of Valheim by approximately 420 Mb
I think that means changing `wav` to `ogg` and indeed there are errors in the log now:
`System.IO.FileNotFoundException: Could not find file '...\valheim\ExportedProject\Assets\AudioClip\Water_BoilLoop.wav'.`

The project works after that though.

**Comment by MSchmoecker** [comment]
Better to report this at https://github.com/heinermann/ValheimExportHelper directly, there seems to be an open issue for this already https://github.com/heinermann/ValheimExportHelper/issues/23

**Comment by heinermann** [comment]
This issue specifically has been fixed for a while now since Dec 22.

Also the linked issue is not the same as this one.
